//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiGetMethod
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Department()
        {
            this.ComDeps = new HashSet<ComDep>();
        }
    
        public int ID { get; set; }
        public int CompanyID { get; set; }
        public string GeneralManagement { get; set; }
        public string MarketingDepartment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComDep> ComDeps { get; set; }
        public virtual Company Company { get; set; }
        public virtual Department Department1 { get; set; }
        public virtual Department Department2 { get; set; }
    }
}
